### ISSUE TITLE
Advanced Hooks -> useCallback section misunderstanding.

### ISSUE THREAD

**Issue by AlexBeje** [reactbyexample/react-by-example#1]
Hello,

I was reading the documentation you created and found out something that doesn't really make sense to me.

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/54982557/105816067-1706b680-5fb4-11eb-84bd-107726fe49e4.png">

Here in this section, we have this explanation of useCallback:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/54982557/105816145-3867a280-5fb4-11eb-90d0-eee9e7e30ffa.png">

I don't really get what is the meaning of it, I might be wrong but I think you were trying to say that `{() => ...} !== (() => ...)` or `useCallback(() => ...) !== (() => ...)`, I am not sure.

---

PS. Also there is a small misspelling error in the useCallback section: `const memoizedFn = useCallback(fn, deps)`, it's `const memorizedFn = ...`. Same issue in the useMemo section.

---

Thank you for making this guide happen and for your time reading this post!

Regards,
Alex.

**Comment by bashforgo** [comment]
Hi Alex,

Try running this `(() => null) === (() => null)` in your console. The implementations are identical, yet they are not `===`.

React uses `===` (or more precisely `Object.is`, which is very similar) to check for changes.

If you "inline" a callback (e.g. `<button onClick={() => setOpen(false)}>close</button>`) React will see this as a new function on every render. If you wrap the callback with `useCallback`, then the hook will return the same function (i.e. they are `===`) on every render, and therefore React can optimize away an update. Now this will not really cause performance issues with a simple `button`, but it helps a lot with more complex components.

Does this make more sense now? How can I express this in a clear but concise way?

---

It's not a typo. [Memoization](https://en.wikipedia.org/wiki/Memoization) is a technique where you use memory to speed up computation by remembering previous return values of a function. I should probably thow in a link in there somewhere. If you want to try this out, check out [`mem`](https://www.npmjs.com/package/mem) on npm.

Thanks for your question,
Bash
